version: "3.6"
volumes:
  sparkws:
    name: "sparkws"
    driver: local

services:
  master:
    image: hamidelmaazouz/sparkmaster:s3.2.0-h3.2-j11
    container_name: sparkmaster
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - sparkws:/opt/sparkws
  sparkrkworker1:
    image: hamidelmaazouz/sparkworker:s3.2.0-h3.2-j11
    container_name: sparkworker1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - sparkws:/opt/sparkws
    depends_on:
      - sparkmaster
  sparkworker2:
    image: hamidelmaazouz/sparkworker:s3.2.0-h3.2-j11
    container_name: sparkworker2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - sparkws:/opt/sparkws
  sparkworker3:
    image: hamidelmaazouz/sparkworker:s3.2.0-h3.2-j11
    container_name: sparkworker3
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    volumes:
      - sparkws:/opt/sparkws
    depends_on:
      - sparkmaster